# .markdownlint.yaml - Markdown linting rules

# Disable overly strict rules for technical documentation
MD013: false # Line length - code examples often exceed 80 chars
MD041: false # First line heading - not required for all files
MD025: false # Multiple top-level headings - acceptable in long docs
MD029: false # Ordered list item prefix - allow flexible numbering
MD035: false # Horizontal rule style - allow any style
MD036: false # Emphasis as heading - allow for examples/notes
MD040: false # Fenced code language - not always applicable
MD046: false # Code block style - allow both fenced and indented

# Keep other quality checks enabled
default: true

# Configure specific rules if needed
MD024:
  siblings_only: true # Allow duplicate headings if not siblings

MD033: false # Allow inline HTML for special formatting
MD034: false # Allow bare URLs in documentation
